//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutocadPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutocadPlugin.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offset Line.
        /// </summary>
        public static string AddOffsetLineButton {
            get {
                return ResourceManager.GetString("AddOffsetLineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotate Polyline.
        /// </summary>
        public static string AnnotatePolylineButton {
            get {
                return ResourceManager.GetString("AnnotatePolylineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Numbers To Road Lines.
        /// </summary>
        public static string AnnotateRoadLinesCheckBox {
            get {
                return ResourceManager.GetString("AnnotateRoadLinesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert To Road Line.
        /// </summary>
        public static string ConvertLineButton {
            get {
                return ResourceManager.GetString("ConvertLineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Road Line.
        /// </summary>
        public static string DrawLineButton {
            get {
                return ResourceManager.GetString("DrawLineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Sign Report.
        /// </summary>
        public static string GenerateSignReportButton {
            get {
                return ResourceManager.GetString("GenerateSignReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatch Functions.
        /// </summary>
        public static string HatchesCategory {
            get {
                return ResourceManager.GetString("HatchesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatch From Polyline.
        /// </summary>
        public static string HatchFromPolylineButton {
            get {
                return ResourceManager.GetString("HatchFromPolylineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Sign.
        /// </summary>
        public static string InsertSignButton {
            get {
                return ResourceManager.GetString("InsertSignButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language: .
        /// </summary>
        public static string LanguageComboBox {
            get {
                return ResourceManager.GetString("LanguageComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linetype File.
        /// </summary>
        public static string LinetypePathTextBoxLabel {
            get {
                return ResourceManager.GetString("LinetypePathTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Width File: .
        /// </summary>
        public static string LineWidthPathTextBoxLabel {
            get {
                return ResourceManager.GetString("LineWidthPathTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Markings.
        /// </summary>
        public static string RoadMarkingsCategory {
            get {
                return ResourceManager.GetString("RoadMarkingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Post Scale:.
        /// </summary>
        public static string SignPostScaleTextBox {
            get {
                return ResourceManager.GetString("SignPostScaleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Scale:.
        /// </summary>
        public static string SignScaleTextBox {
            get {
                return ResourceManager.GetString("SignScaleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Sign Catalogue:.
        /// </summary>
        public static string StreetSignPathTextBoxLabel {
            get {
                return ResourceManager.GetString("StreetSignPathTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Signs.
        /// </summary>
        public static string StreetSignsCategory {
            get {
                return ResourceManager.GetString("StreetSignsCategory", resourceCulture);
            }
        }
    }
}
